/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: 'root' },

    
  ],
  apiSidebar: [

    {
      label: 'Agent',
      collapsed: true,
      type: 'category',
      link: {
          type: 'generated-index',
          title: 'Agent docs',
          description: 'Generated Agent docs for the OpenAPI spec',
      },
      items: require("./docs/agent/sidebar.ts"),
    },

    {
      label: 'Server',
      collapsed: true,
      type: 'category',
      link: {
          type: 'generated-index',
          title: 'API docs',
          description: 'Generated API docs for the OpenAPI spec',
      },
      items: require("./docs/api/sidebar.ts"),
    }

  ] 

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
};

export default sidebars;
