/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: 'root' },
  ],

  serverSidebar: [
    {
      label: 'Server',
      collapsed: false,
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Server API docs',
        description: 'Generated Server docs for the OpenAPI spec',
      },
      items: require("./docs/server/sidebar.ts"),
    }
  ],

  agentSidebar: [
    {
      label: 'V2',
      collapsed: true,
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Agent V2 API',
        description: 'Agent V2 API — application lifecycle management',
      },
      items: require("./docs/agent/sidebar.ts"),
    },
    {
      label: 'Core',
      collapsed: true,
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Agent Core API',
        description: 'Agent Core API — catalog and discovery services',
      },
      items: require("./docs/agent-core/sidebar.ts"),
    },
    {
      label: 'CDN',
      collapsed: true,
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Agent CDN API',
        description: 'Agent CDN API — connected devices network',
      },
      items: require("./docs/agent-cdn/sidebar.ts"),
    },
  ],
  evnSidebar: [
    {
      label: 'Environment Variables',
      collapsed: true,
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Environment Variables',
        description: 'Environment variable reference for all microservices',
      },
      items: require("./docs/env/sidebar.js").map((item) => ({
        type: /** @type {'doc'} */ ('doc'),
        id: item.id, 
        label: item.label,
      }))
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

};

export default sidebars;
